import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
  # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
]

[bell]
animation = "EaseOutExpo"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
style = "Bold"
family = "JetBrainsMono Nerd Font Mono"

[font.italic]
style = "Medium Italic"
family = "JetBrainsMono Nerd Font Mono"

[font.normal]
style = "Medium"
family = "JetBrainsMono Nerd Font Mono"

[font.bold_italic]
style = "Bold Italic"
family = "JetBrainsMono Nerd Font Mono"

[scrolling]
history = 5000
multiplier = 5

[selection]
save_to_clipboard = true

[window]
blur = true
opacity = 0.85
dynamic_padding = false
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"
decorations = "Buttonless"

[window.padding]
x = 10
y = 15
