[env]
TERM = "xterm-256color"

[font]
size = 17.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"


[window]
blur = true
opacity = 0.50
dynamic_padding = false
startup_mode = "Maximized"
decorations = "Transparent"

[window.padding]
x = 20
y = 20
