#!/usr/bin/env bash
set -e
echo 'removing XCode...'

sudo rm -fr /Applications/Xcode.app
sudo rm -fr ~/Library/Caches/com.apple.dt.Xcode
sudo rm -fr ~/Library/Developer
sudo rm -fr ~/Library/MobileDevice
sudo rm -fr ~/Library/Preferences/com.apple.dt.Xcode.plist
sudo rm -fr /Library/Preferences/com.apple.dt.Xcode.plist
sudo rm -fr /System/Library/Receipts/com.apple.pkg.XcodeExtensionSupport.bom
sudo rm -fr /System/Library/Receipts/com.apple.pkg.XcodeExtensionSupport.plist
sudo rm -fr /System/Library/Receipts/com.apple.pkg.XcodeSystemResources.bom
sudo rm -fr /System/Library/Receipts/com.apple.pkg.XcodeSystemResources.plist

#read 'Do you want to delete customizations? [Y/N]' REPLY
#if [[ ! $REPLY =~ ^[Yy]$ ]]
#then
#  exit 0;
#fi
sudo rm -fr ~/Library/Developer/Xcode/UserData/CodeSnippets
sudo rm -fr ~/Library/Developer/Xcode/UserData/FontAndColorThemes
sudo rm -fr ~/Library/Developer/Xcode/UserData/KeyBindings
sudo rm -fr ~/Library/Developer/Xcode/Templates
sudo rm -fr ~/Library/Preferences/com.apple.dt.Xcode.plist
sudo rm -fr ~/Library/MobileDevice/Provisioning\ Profiles
