#!/usr/bin/env bash

function setup_nmr_dotfiles() {
  # Intentionally mixing tab and space here for pretty output
	cat <<-EOF
    There is a brew.sh and .macos script which makes your Mac
    more friendly for development. I highly recommend to CHECK and
    ADD/EDIT those files before running it.
	EOF
}

setup_nmr_dotfiles
