#!/usr/bin/env bash
set -e
remove() {
  sudo -v

  entry="$1"
  echo -ne "Removing $entry... "
  sudo rm -rf "$entry"

  if [[ ! -e "$entry" ]]; then
    echo -ne "[OK]"
  else
    echo -ne "[FAILED]"
  fi
  echo
}
brew uninstall --cask android-studio
remove /Applications/Android\ Studio.app
remove ~/Library/Preferences/AndroidStudio*
remove ~/Library/Preferences/Google/AndroidStudio*
remove ~/Library/Preferences/com.google.android.*
remove ~/Library/Preferences/com.android.*
remove ~/Library/Application\ Support/AndroidStudio*
remove ~/Library/Application\ Support/Google/AndroidStudio*
remove ~/Library/Logs/AndroidStudio*
remove ~/Library/Logs/Google/AndroidStudio*
remove ~/Library/Caches/AndroidStudio*
remove ~/.AndroidStudio*
remove ~/.gradle
remove ~/AndroidStudioProjects
remove ~/Library/Android*
remove ~/.emulator_console_auth_token
remove ~/Library/Preferences/Google/AndroidStudio*
remove ~/Library/Caches/Google/AndroidStudio*
remove ~/Library/Logs/Google/AndroidStudio*
