#!/usr/bin/env bash
set -e
remove() {
  entry="$1"

  echo -ne "Removing $entry... "
  sudo rm -rf "$entry"

  if [[ ! -e "$entry" ]]; then
    echo -ne "[OK]"
  else
    echo -ne "[FAILED]"
  fi
  echo
}

brew uninstall --cask --zap --quiet brave-browser
remove "/Applications/Brave\ Browser.app"
remove "~/Library/Application\ Support/BraveSoftware/"
remove "~/Library/Application\ Support/CrashReporter/Brave*"
remove "~/Library/Preferences/com.brave*"
remove "~/Library/Saved\ Application\ State/com.brave.Browser.savedState"
remove "~/Library/Brave*"
remove "~/Library/Speech/Speakable\ Items/Application\ Speakable\ Items/Brave/"
remove "~/Library/LaunchAgents/com.brave.*"
remove "~/Library/Caches/com.brave*"
remove "~/Library/Caches/com.brave*"
remove "~/Library/Caches/com.brave*"
remove "~/Library/Application\ Support/Brave*"
remove "~/Applications/Brave*"
