#!/usr/bin/env bash
set -e
remove() {
  entry="$1"

  echo -ne "Removing $entry... "
  sudo rm -rf "$entry"

  if [[ ! -e "$entry" ]]; then
    echo -ne "[OK]"
  else
    echo -ne "[FAILED]"
  fi
  echo
}

brew uninstall --zap --quiet --cask docker
remove /Applications/Docker.app
remove /usr/local/bin/docker
remove /usr/local/bin/docker-machine
remove /usr/local/bin/com.docker.cli
remove /usr/local/bin/docker-compose
remove /usr/local/bin/docker-compose-v1
remove /usr/local/bin/docker-credential-desktop
remove /usr/local/bin/docker-credential-ecr-login
remove /usr/local/bin/docker-credential-osxkeychain
remove /usr/local/bin/hub-tool
remove /usr/local/bin/hyperkit
remove /usr/local/bin/kubectl.docker
remove /usr/local/bin/vpnkit
remove ~/.docker
remove ~/Library/Containers/com.docker.docker
remove ~/Library/Application\ Support/Docker\ Desktop
remove ~/Library/Group\ Containers/group.com.docker
remove ~/Library/HTTPStorages/com.docker.docker.binarycookies
remove /Library/PrivilegedHelperTools/com.docker.vmnetd
remove /Library/LaunchDaemons/com.docker.vmnetd.plist
remove ~/Library/Logs/Docker\ Desktop
remove /usr/local/lib/docker
remove ~/Library/Preferences/com.docker.docker.plist
remove ~/Library/Saved\ Application\ State/com.electron.docker-frontend.savedState
remove ~/Library/Preferences/com.electron.docker-frontend.plist
