#!/usr/bin/env bash
set -e
echo -n 'removing Microsoft Edge...'
rm -fr /Applications/Microsoft\ Edge.app/
rm -fr ~/Library/Application\ Support/Microsoft/EdgeUpdater/
rm -fr ~/Library/Application\ Support/CrashReporter/Microsoft*
rm -fr ~/Library/Preferences/com.microsoft.autoupdate*
rm -fr ~/Library/Caches/com.microsoft.Edge*
rm -fr ~/Library/Saved\ Application\ State/com.microsoft.Edge*
rm -fr ~/Library/Microsoft/EdgeUpdater/
rm -fr ~/Library/Google/Microsoft\ Edge*
rm -fr ~/Library/Speech/Speakable\ Items/Application\ Speakable\ Items/Microsoft\ Edge*
rm -fr ~/Library/LaunchAgents/com.microsoft.Edge*
rm -fr ~/Library/Preferences/com.google.Keystone.Agent.plist
rm -fr ~/Library/Caches/com.google.Keystone*
rm -fr ~/Library/Caches/com.google.SoftwareUpdate
rm -rf ~/Applications/Edge\ Apps
echo ' [done]'
