#!/usr/bin/env bash
set -e

remove() {
  sudo -v

  entry="$1"
  echo -ne "Removing $entry... "
  sudo rm -rf "$entry"

  if [[ ! -e "$entry" ]]; then
    echo -ne "[OK]"
  else
    echo -ne "[FAILED]"
  fi
  echo
}

brew uninstall --cask --quiet --zap microsoft-edge
remove /Applications/Microsoft\ Edge.app/
remove ~/Library/Caches/Microsoft\ Edge
remove ~/Library/Preferences/com.microsoft.edge*
remove ~/Library/Application\ Support/Microsoft/EdgeUpdater/
remove ~/Library/Application\ Support/CrashReporter/Microsoft*
remove ~/Library/Preferences/com.microsoft.autoupdate*
remove ~/Library/Caches/com.microsoft.Edge*
remove ~/Library/Saved\ Application\ State/com.microsoft.Edge*
remove ~/Library/Microsoft/EdgeUpdater/
remove ~/Library/Application\ Support/Microsoft\ Edge*
remove ~/Library/Speech/Speakable\ Items/Application\ Speakable\ Items/Microsoft\ Edge*
remove ~/Library/LaunchAgents/com.microsoft.Edge*
remove ~/Library/Preferences/com.microsoft.edge*
remove ~/Library/Caches/com.microsoft.edge*
remove ~/Library/Caches/com.microsoft.EdgeUpdater
remove ~/Applications/Edge\ Apps
