#!/usr/bin/env bash
set -e
remove() {
  sudo -v

  entry="$1"
  echo -ne "Removing $entry... "
  sudo rm -rf "$entry"

  if [[ ! -e "$entry" ]]; then
    echo -ne "[OK]"
  else
    echo -ne "[FAILED]"
  fi
  echo
}

brew uninstall --zap --force --quiet neovim
remove $HOME/.cache/nvim
remove $HOME/.config/nvim
remove $HOME/.local/share/nvim
remove $HOME/.local/state/nvim

