#!/usr/bin/env bash
set -e
remove() {
  entry="$1"

  echo -ne "Removing $entry... "
  sudo rm -rf "$entry"

  if [[ ! -e "$entry" ]]; then
    echo -ne "[OK]"
  else
    echo -ne "[FAILED]"
  fi
  echo
}

remove "/Applications/VMware Fusion.app"
remove "/Library/Application Support/VMware"
remove "/Library/Application Support/VMware Fusion"
remove "/Library/Preferences/VMware Fusion"
remove "/private/var/root/Library/Logs/VMware"
remove "/private/var/db/vmware"
remove "/Library/Logs/VMware/"
remove "/Library/Logs/VMware Fusion Services.log"
remove "/Library/Logs/DiagnosticReports/vmware*"
remove "/private/var/run/vmware"
remove "/private/var/run/VMware Fusion Services.lock"
remove "/private/var/run/VMware Fusion Services.sock"
remove "/private/var/root/Library/Preferences/VMware Fusion"
remove "/var/db/BootCaches/*/app.com.vmware.fusion.playlist"
remove "~/Library/Application Support/VMware Fusion"
remove "~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.vmware.fusion.sfl"
remove "~/Library/Caches/com.vmware.fusion"
remove "~/Library/Preferences/VMware Fusion"
remove "~/Library/Logs/VMware"
remove "~/Library/Logs/VMware Fusion"
remove "~/Library/Preferences/VMware Fusion"
remove "~/Library/Preferences/com.vmware.fusion.LSSharedFileList.plist"
remove "~/Library/Preferences/com.vmware.fusion.plist"
remove "~/Library/Preferences/com.vmware.fusionStartMenu.plist"
remove "~/Library/Preferences/com.vmware.fusion.LSSharedFileList.plist"
remove "~/Library/Preferences/com.vmware.fusion.LSSharedFileList.plist.lockfile"
remove "~/Library/Preferences/com.vmware.fusion.plist"
remove "~/Library/Preferences/com.vmware.fusion.plist.lockfile"
remove "~/Library/Preferences/com.vmware.fusionDaemon.plist"
remove "~/Library/Preferences/com.vmware.fusionDaemon.plist.lockfile"
remove "~/Library/Preferences/com.vmware.fusionStartMenu.plist"
remove "~/Library/Preferences/com.vmware.fusionStartMenu.plist.lockfile"
