#!/usr/bin/env bash
set -e
remove() {
  sudo -v

  entry="$1"
  echo -ne "Removing $entry... "
  sudo rm -rf "$entry"

  if [[ ! -e "$entry" ]]; then
    echo -ne "[OK]"
  else
    echo -ne "[FAILED]"
  fi
  echo
}

brew uninstall --cask --zap visual-studio-code
remove ~/Library/Preferences/com.microsoft.VSCode.helper.plist
remove ~/Library/Preferences/com.microsoft.VSCode.plist
remove ~/Library/Caches/com.microsoft.VSCode
remove ~/Library/Caches/com.microsoft.VSCode.ShipIt/
remove ~/Library/Application\ Support/Code/
remove ~/Library/Saved\ Application\ State/com.microsoft.VSCode.savedState/
remove ~/.vscode
remove ~/Library/Application\ Support/Code
remove ~/Library/Application\ Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.microsoft.vscode.sfl*
remove ~/Library/Caches/com.microsoft.VSCode.ShipIt
remove ~/Library/Caches/com.microsoft.VSCode
remove ~/Library/Preferences/ByHost/com.microsoft.VSCode.ShipIt.*.plist
remove ~/Library/Preferences/com.microsoft.VSCode.helper.plist
remove ~/Library/Preferences/com.microsoft.VSCode.plist
remove ~/Library/Saved\ Application\ State/com.microsoft.VSCode.savedState
