#!/usr/bin/env bash
set -e
remove() {
  sudo -v

  entry="$1"
  echo -ne "Removing $entry... "
  sudo rm -rf "$entry"

  if [[ ! -e "$entry" ]]; then
    echo -ne "[OK]"
  else
    echo -ne "[FAILED]"
  fi
  echo
}

remove /Applications/Xcode.app
remove ~/Library/Caches/com.apple.dt.Xcode
remove ~/Library/Developer
remove ~/Library/MobileDevice
remove ~/Library/Preferences/com.apple.dt.Xcode.plist
remove /Library/Preferences/com.apple.dt.Xcode.plist
remove /System/Library/Receipts/com.apple.pkg.XcodeExtensionSupport.bom
remove /System/Library/Receipts/com.apple.pkg.XcodeExtensionSupport.plist
remove /System/Library/Receipts/com.apple.pkg.XcodeSystemResources.bom
remove /System/Library/Receipts/com.apple.pkg.XcodeSystemResources.plist
remove ~/Library/Developer/Xcode/UserData/CodeSnippets
remove ~/Library/Developer/Xcode/UserData/FontAndColorThemes
remove ~/Library/Developer/Xcode/UserData/KeyBindings
remove ~/Library/Developer/Xcode/Templates
remove ~/Library/Preferences/com.apple.dt.Xcode.plist
remove ~/Library/MobileDevice/Provisioning\ Profiles
