#!/usr/bin/env bash
set -e

# stop yabai
yabai --stop-service

# remove service file
yabai --uninstall-service

# uninstall the scripting addition
sudo yabai --uninstall-sa

# uninstall yabai
brew uninstall --zap yabai

# these are logfiles that may be created when running yabai as a service.
rm -rf /tmp/yabai_$USER.out.log
rm -rf /tmp/yabai_$USER.err.log

# remove config and various temporary files
rm ~/.yabairc
rm /tmp/yabai_$USER.lock
rm /tmp/yabai_$USER.socket
rm /tmp/yabai-sa_$USER.socket

# unload the scripting addition by forcing a restart of Dock.app
killall Dock
