#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

# -----------------------------
# Blocks: Left segments
# -----------------------------
[[blocks]]
  alignment = "left"
  type = "prompt"

  [[blocks.segments]]
    background = "black"
    foreground = "white"
    leading_diamond = "\ue0b6"
    style = "diamond"
    template = " {{ if .WSL }}WSL at {{ end }}{{.Icon}} "
    type = "os"

  [[blocks.segments]]
    background = "#313244"
    foreground = "#e4e4e4"
    powerline_symbol = "\ue0b4"
    style = "powerline"
    template = "{{ .Path }} "
    type = "path"

    [blocks.segments.properties]
      folder_icon = "  .."
      home_icon = ' 󱂵 ~'
      style = "agnoster_short"
      folder_separator_icon = "/"
      hide_root_location = true
      max_depth = 2

  [[blocks.segments]]
    background = "#fcbc05"
    background_templates = [
      "{{ if or (.Working.Changed) (.Staging.Changed) }}#fcbc05{{ end }}",
      "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#fcbc05{{ end }}",
      "{{ if gt .Ahead 0 }}#fcbc05{{ end }}",
      "{{ if gt .Behind 0 }}#fcbc05{{ end }}"
    ]
    foreground = "#212121"
    powerline_symbol = "\ue0b4"
    style = "powerline"
    template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
    type = "git"

    [blocks.segments.properties]
    branch_icon = " "
    fetch_stash_count = true
    fetch_status = true
    fetch_upstream_icon = true

# -----------------------------
# Blocks: Right segments
# - status
# - node
# - angular
# - bun
# - java
# - php
# - python
# - ruby
# - lua
# - golang
# - rust
# - project
# - executiontime
# -----------------------------
[[blocks]]
  alignment = "right"
  type = "prompt"


  [[blocks.segments]]
    background = "#444"
    background_templates = [ "{{ if gt .Code 0 }}#cc2222{{ end }}" ]
    foreground = "#d3d7cf"
    leading_diamond = ""
    trailing_diamond = ""
    style = "diamond"
    template = " {{ if gt .Code 0 }}{{ reason .Code }}{{ else }}{{ end }} "
    type = "status"
    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    type = "node"
    style = "diamond"
    leading_diamond = ""
    trailing_diamond = ""
    foreground = "#36454F"
    background = "#95ffa5"
    template = "  {{ .Full }}"

  [[blocks.segments]]
    type = "angular"
    style = "diamond"
    leading_diamond = ""
    trailing_diamond = ""
    foreground = "#36454F"
    background = "#95ffa5"
    template = "  {{ .Full }}"

  [[blocks.segments]]
    type = "bun"
    style = "diamond"
    leading_diamond = ""
    trailing_diamond = ""
    foreground = "#36454F"
    background = "#3C82F6"
    template = "🥟 {{ .Full }}"

  [[blocks.segments]]
    type = "java"
    style = "diamond"
    leading_diamond = ""
    trailing_diamond = ""
    foreground = "#36454F"
    background = "#95ffa5"
    template = " 󰬷 {{ .Full }}"

  [[blocks.segments]]
    type = "php"
    style = "diamond"
    leading_diamond = ""
    trailing_diamond = ""
    foreground = "#36454F"
    background = "#95ffa5"
    template = "  {{ .Full }}"

  [[blocks.segments]]
    type = "python"
    style = "diamond"
    leading_diamond = ""
    trailing_diamond = ""
    foreground = "#36454F"
    background = "#95ffa5"
    template = "  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}"

  [[blocks.segments]]
    type = "ruby"
    style = "diamond"
    leading_diamond = ""
    trailing_diamond = ""
    foreground = "#36454F"
    background = "#95ffa5"
    template = "  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}"

  [[blocks.segments]]
    type = "lua"
    style = "diamond"
    leading_diamond = ""
    trailing_diamond = ""
    foreground = "#36454F"
    background = "#95ffa5"
    template = " 󰢱 {{ .Full }}"

  [[blocks.segments]]
    type = "go"
    style = "diamond"
    leading_diamond = ""
    trailing_diamond = ""
    foreground = "#36454F"
    background = "#95ffa5"
    template = " {{ .Full }}"

  [[blocks.segments]]
    type = "rust"
    style = "diamond"
    leading_diamond = ""
    trailing_diamond = ""
    foreground = "#36454F"
    background = "#95ffa5"
    template = " {{ .Full }}"

  [[blocks.segments]]
    type = "project"
    style = "diamond"
    leading_diamond = ""
    trailing_diamond = ""
    foreground = "#232f3e"
    background = "#b389ff"
    template = " {{ if .Error }}{{ .Error }}{{ else }}{{ if .Version }} {{.Version}}{{ end }}{{ end }}"

  [[blocks.segments]]
    background = "#203348"
    foreground = "#ccc"
    style = "diamond"
    template = " 󱦟 {{ .FormattedMs }}"
    leading_diamond = ""
    trailing_diamond = ""
    type = "executiontime"


# -----------------------------
# Blocks: Terminal Input
# - prompt: magenta when ok and red when error
# - transient_prompt
# - secondary_prompt
# - debug_prompt
# -----------------------------
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❯❯ '

[debug_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = 'Debugging ❯❯ '


# -----------------------------
# Tootips section
# - terraform
# - aws
# - docker
# - azure
# - gcp
# - kubectl
# -----------------------------
[[tooltips]]
  type = "terraform"
  tips = [ "terraform", "tf", "tfa", "tfc", "tfd", "tff", "tfi", "tfo", "tfp", "tfs", "tfsh", "tft", "tfv" ]
  style = "plain"
  template = "󱁢 {{.Version}}"
  foreground = "#b18bdd"
  [tooltips.properties]
    fetch_version = true

[[tooltips]]
  type = "aws"
  tips = [ "aws", "eb", "ecs", "eksctl"]
  style = "plain"
  foreground = "#ff9a01"
  template = " 󰸏 {{.Profile}}{{if .Region}}@{{.Region}}{{end}}"

[[tooltips]]
  type = "docker"
  tips = [ "docker", "docker-compose", "dc", "dcleanup"]
  style = "plain"
  foreground = "#cda4f6"

[[tooltips]]
  type = "az"
  tips = [ "az"]
  style = "plain"
  foreground = "#33b0e5"
  template = "  {{ .EnvironmentName }}"

[[tooltips]]
  type = "gcp"
  tips = [ "gcp", "gcloud"]
  style = "plain"
  foreground = "#34a853"
  template = "  {{.Project}} :: {{.Account}} "

[[tooltips]]
  type = "helm"
  tips = [ "gcp", "gcloud"]
  style = "plain"
  foreground = "#004daa"
  template = "  {{.Project}} :: {{.Account}} "

[[tooltips]]
  type = "kubectl"
  tips = [ "kubectl", "k8s", "k9s", "krew"]
  style = "plain"
  foreground = "#326ce5"
  template = " 󱃾 {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}} "
  # [tooltips.properties.context_aliases]
  #   "arn:aws:eks:eu-west-1:1234567890:cluster/posh" = "posh"
