#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
alignment = "left"
type = "prompt"

  [[blocks.segments]]
  background = "black"
  foreground = "white"
  leading_diamond = "\ue0b6"
  style = "diamond"
  template = " {{ if .WSL }}WSL at {{ end }}{{.Icon}} "
  type = "os"

  [[blocks.segments]]
  background = "#313244"
  foreground = "#e4e4e4"
  powerline_symbol = "\ue0b4"
  style = "powerline"
  template = "  {{ .Path }}"
  type = "path"

    [blocks.segments.properties]
    home_icon = "~"
    style = "folder"

  [[blocks.segments]]
  background = "#cba6f7"
  background_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#cba6f7{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#cba6f7{{ end }}",
  "{{ if gt .Ahead 0 }}#cba6f7{{ end }}",
  "{{ if gt .Behind 0 }}#cba6f7{{ end }}"
]
  foreground = "#000000"
  powerline_symbol = "\ue0b4"
  style = "powerline"
  template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
  type = "git"

    [blocks.segments.properties]
    branch_icon = " "
    fetch_stash_count = true
    fetch_status = true
    fetch_upstream_icon = true



[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❯❯ '
