console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  airbnb_red = '#FF5A5F'
  blue = '#b389ff'
  charcoal = '#43302E'
  crayola = '#313244'
  green = '#95ffa5'
  ink_black = '#212122'
  pale_navy = '#cdd6f4'
  space_grey = '#717378'

[debug_prompt]
  template = 'Debugging ❯❯ '
  foreground = 'magenta'
  background = 'transparent'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'magenta'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}green{{end}}']

[[tooltips]]
  template = '󱁢 {{.Version}}'
  foreground = '#b18bdd'
  type = 'terraform'
  style = 'plain'
  tips = ['terraform', 'tf', 'tfa', 'tfc', 'tfd', 'tff', 'tfi', 'tfo', 'tfp', 'tfs', 'tfsh', 'tft', 'tfv']

  [tooltips.properties]
    fetch_version = true

[[tooltips]]
  template = ' 󰸏 {{.Profile}}{{if .Region}}@{{.Region}}{{end}}'
  foreground = '#ff9a01'
  type = 'aws'
  style = 'plain'
  tips = ['aws', 'eb', 'ecs', 'eksctl']

[[tooltips]]
  foreground = '#cda4f6'
  type = 'docker'
  style = 'plain'
  tips = ['docker', 'docker-compose', 'dc', 'dcleanup']

[[tooltips]]
  template = '  {{ .EnvironmentName }}'
  foreground = '#33b0e5'
  type = 'az'
  style = 'plain'
  tips = ['az']

[[tooltips]]
  template = '  {{.Project}} :: {{.Account}} '
  foreground = '#34a853'
  type = 'gcp'
  style = 'plain'
  tips = ['gcp', 'gcloud']

[[tooltips]]
  template = '  {{.Project}} :: {{.Account}} '
  foreground = '#004daa'
  type = 'helm'
  style = 'plain'
  tips = ['gcp', 'gcloud']

[[tooltips]]
  template = ' 󱃾 {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}} '
  foreground = '#326ce5'
  type = 'kubectl'
  style = 'plain'
  tips = ['kubectl', 'k8s', 'k9s', 'krew']

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    leading_diamond = ''
    foreground = '#080808'
    background = 'p:space_grey'
    type = 'os'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ if not .Writable }} 󰌾 {{end}}{{ .Path }}'
    foreground = 'p:pale_navy'
    powerline_symbol = ''
    background = 'p:crayola'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_icon = '  ..'
      folder_separator_icon = '/'
      hide_root_location = true
      home_icon = ' 󱂵 ~'
      max_depth = 2
      style = 'agnoster_short'

      [blocks.segments.properties.mapped_locations]
        '~/Devzone' = ' 󰲋 Devzone'
        '~/Documents' = ' 󱔗 Documents'
        '~/Downloads' = '  Downloads'
        '~/Movies' = '  Movies'
        '~/Music' = ' 󰝚 Music'
        '~/Pictures' = '  Pictures'

  [[blocks.segments]]
    foreground = 'p:ink_black'
    powerline_symbol = ''
    background = '#fcbc05'
    type = 'git'
    style = 'powerline'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#fcbc05{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#fcbc05{{ end }}', '{{ if gt .Ahead 0 }}#fcbc05{{ end }}', '{{ if gt .Behind 0 }}#fcbc05{{ end }}']

    [blocks.segments.properties]
      branch_icon = ' '
      cache_duration = 'none'
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ if gt .Code 0 }}{{ reason .Code }}{{ else }}{{ end }} '
    foreground = 'p:green'
    background = '#444'
    type = 'status'
    style = 'diamond'
    background_templates = ['{{ if gt .Code 0 }}#cc2222{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'

  [[blocks.segments]]
    trailing_diamond = ''
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}{{ end }}'
    foreground = 'p:charcoal'
    background = 'p:green'
    type = 'cmake'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    trailing_diamond = ''
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}{{ end }}'
    foreground = 'p:charcoal'
    background = 'p:green'
    type = 'node'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    trailing_diamond = ''
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
    foreground = 'p:charcoal'
    background = 'p:green'
    type = 'angular'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    trailing_diamond = ''
    template = '🥟 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
    foreground = 'p:charcoal'
    background = '#3C82F6'
    type = 'bun'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    trailing_diamond = ''
    template = ' 󰬷 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
    foreground = 'p:charcoal'
    background = 'p:green'
    type = 'java'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    trailing_diamond = ''
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
    foreground = 'p:charcoal'
    background = 'p:green'
    type = 'mvn'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    trailing_diamond = ''
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
    foreground = 'p:charcoal'
    background = 'p:green'
    type = 'php'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    trailing_diamond = ''
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}{{ end }}'
    foreground = 'p:charcoal'
    background = 'p:green'
    type = 'python'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    trailing_diamond = ''
    template = ' 󰢱 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
    foreground = 'p:charcoal'
    background = 'p:green'
    type = 'lua'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    trailing_diamond = ''
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
    foreground = 'p:charcoal'
    background = 'p:green'
    type = 'rust'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    trailing_diamond = ''
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ if .Version }} {{.Version}}{{ end }}{{ end }}'
    foreground = 'p:ink_black'
    background = 'p:blue'
    type = 'project'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    trailing_diamond = ''
    template = ' 󱦟 {{ .FormattedMs }}'
    foreground = 'p:pale_navy'
    background = 'p:airbnb_red'
    type = 'executiontime'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}green{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
