[settings]
experimental                                              = true
cache_prune_age                                           = "3d"
legacy_version_file                                       = true
plugin_autoupdate_last_check_duration                     = "1d"
idiomatic_version_file_enable_tools                       = ["node"]

[tools]
deno                                                      = "latest"
maven                                                     = "latest"
node                                                      = ["latest", "lts", "lts-krypton", "lts-jod"]
java                                                      = ["zulu-crac-26.32.203.0", "zulu-crac-25.36.205.0", "zulu-crac-21.52.203.0", "zulu-crac-17.68.203.0"]

[tool_alias.java.versions]
26                                                        = "zulu-crac-26.32.203.0"
25                                                        = "zulu-crac-25.36.205.0"
21                                                        = "zulu-crac-21.52.203.0"
17                                                        = "zulu-crac-17.68.203.0"
